#!/bin/bash

#DEFINING VARIABLES
notes=School/Notes/pythonClass                                 #File Location
touch School/Notes/pythonClass/newestFile.log                  #Updates Log File
newstFileLog=School/Notes/pythonClass/newestFile.log           #Defines Log file Variable
newstFile=$(cat $newstFileLog)                                 #Defines Log file contents as Variable
space=`echo $'\n.'`
space=${space%.}
read -p "What would you like your file name to be?$space" fileName

#FUNCTIONS

findNumber () {                               #Finds and updates what notes we're on and converts to int if not already one
    #findNumber <string> <subString>
    fileNumber=${1%%$2*}
    if [ ${fileNumber:0:1} = 0 ]; then
        fileNumber=${fileNumber/0}
    fi
    fileNumber=$(($fileNumber + 1))
}

fileExist () {                                #Tests for existence of file while returning own str
    #fileExist <fileName>
    errorClarity=$(ls $1)
    error=$?
    if ! [ $error -eq 0 ]; then
        echo "Check if $newstFileLog has the latest file."
    fi
}

fileMakingProcess () {                        #Creates and opens file in nano
    #fileMakingProcess <int> <string> <typeOfFile>
    if [[ $1 -lt 10 && $1 -gt 0 ]]; then
        local file="0${1}_${2}.${3}"
        #touch $notes/$file
        nano $notes/$file
        echo $file > $newstFileLog
    else
        local file="${1}_${2}.${3}"
        #touch $notes/$file
        nano $notes/$file
        echo $file > $newstFileLog
    fi
    echo "File successfully created."
}

#SCRIPTRUN

findNumber $newstFile _
fileExist $notes/$newstFile
fileMakingProcess $fileNumber $fileName "py"
